<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2022/23</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 6</span>
    </b></span></div>

In [7]:
from algoritmos import *

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El objetivo de esta práctica es definir funciones <span style="font-family: Courier">Python</span> para resolver sistemas de ecuaciones lineales utilizando para ello <b>factorizaciones</b> de tipo $LU$ y de Cholesky.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Recordamos que dada $A\in\mathcal{M}_n(\mathbb{K})$ inversible, se llama <b>factorización</b> $LU$ a la descomposición, si es posible, $A=L\,U$, siendo $L\in\mathcal{M}_n(\mathbb{K})$ triangular inferior, inversible y con unos en la diagonal principal y $U\in\mathcal{M}_n(\mathbb{K})$ triangular superior e inversible. Esta factorización es posible si y solamente si todas las submatrices principales de $A$ son también inversibles, siendo además única.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    La factorización $LU$ de una matriz $A$, cuando es posible, está asociada de forma natural a un método directo de resolución del sistema $AX=B$, llamado <b>método</b> $LU$, en el que se pueden diferenciar dos etapas:<ul>
    <li>determinación de la factorización $A=L\,U$ de la matriz;</li>
    <li>resolución mediante un proceso de descenso seguido de uno de remonte del sistema lineal, ya que
\[
A\,X = B\quad \Longleftrightarrow\quad L\,Y = B \quad \mbox{y} \quad U\,X=Y\,.
\]</li></ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Escribir una función <span style="font-family: Courier">Python</span>, de nombre <span style="font-family: Courier">facto_lu()</span>, que implemente el algoritmo de la <b>factorización</b> $LU$ de una matriz $A$. Recordamos que realizar la factorización $LU$ de una matriz es equivalente a realizar el método de Gauss sin permutación de filas en cada iteración; la función debe prever que la matriz dada verifique las hipótesis necesarias para que dicha factorización sea posible.
    <br>
    Dicha función debe tener un único argumento de entrada, que es la matriz $A$ y dos argumentos de salida, siendo el primero de tipo boleano (para indicar si se ha realizado o no dicha factorización) y el segundo una única matriz que debe contener en la parte triangular superior la matriz $U$ y en la parte estrictamente triangular inferior la matrz $L$ (cuyos elementos diagonales, que valen 1, no se guardan).
    </span></div>

In [5]:
def facto_lu(A):
    m, n = shape(A)
    if m != n:
        return False, "Error facto_lu: error en las dimensiones."
    if A.dtype == complex:
        lu = array(A, dtype=complex)
    else:
        lu = array(A, dtype=float)
    for k in range(n-1):
        if abs(lu[k, k]) >= 1e-200:
            for i in range(k+1, n):
                lu[i, k] = lu[i, k]/lu[k, k]
                lu[i, k+1:] -= lu[i, k]*lu[k, k+1:]
        else:
            return False, "Error facto_lu: no admite factorización."
    return True, lu

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Realizar, si es posible, la factorización $LU$ de las siguientes matrices:
\[
\mbox{(a)} \quad A = \left(\begin{array}{rrrr} 2 & -1 & 4 & 0 \\ 4 & -1 & 5 & 1 \\ -2 & 2 & -2 & 3 \\ 0 & 3 & -9 & 4 \end{array} \right)\,;
\qquad
\mbox{(b)} \quad A = \left(\begin{array}{rrrr} 3 & -2 & 6 & -5 \\ 18 & -12 & 41 & -39 \\ -27 & 18 & -62 & 54 \\ 9 & 14 & 15 & -47 \end{array} \right)\,.
\]
    Comprobar la exactitud de los cálculos realizados, verificando que $A-L\,U=0$.
    </span></div>

In [2]:
# Ejercicio 2-a.
print("Ejercicio 2-a.")
A = array([[2, -1, 4, 0], [4, -1, 5, 1], [-2, 2, -2, 3], [0, 3, -9, 4]])
print("Matriz: A = ", A)
exito, lu = facto_lu(A)
if exito:
    print("Factorización: lu = ", lu)
    U = triu(lu)
    print("Matriz: U = ", U)
    L = eye(4) + tril(lu, k=-1)
    print("Matriz: L = ", L)
    print("Comprobación: ||A-L@U||_2 = ", norma_mat(A - L@U, 2)) 
else:
    print("Error ", lu)

Ejercicio 2-a.
Matriz: A =  [[ 2 -1  4  0]
 [ 4 -1  5  1]
 [-2  2 -2  3]
 [ 0  3 -9  4]]
Factorización: lu =  [[ 2. -1.  4.  0.]
 [ 2.  1. -3.  1.]
 [-1.  1.  5.  2.]
 [ 0.  3.  0.  1.]]
Matriz: U =  [[ 2. -1.  4.  0.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  5.  2.]
 [ 0.  0.  0.  1.]]
Matriz: L =  [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [-1.  1.  1.  0.]
 [ 0.  3.  0.  1.]]
Comprobación: ||A-L@U||_2 =  0.0


In [8]:
# Ejercicio 2-b.
print("Ejercicio 2-b.")
A = array([[3, -2, 6, -5], [18, -12, 41, -39], [-27, 18, -62, 54], [9, 14, 15, -47]])
print("Matriz: A = ", A)
exito, lu = facto_lu(A)
if exito:
    print("Factorización: lu = ", lu)
    U = triu(lu)
    print("Matriz: U = ", U)
    L = eye(4) + tril(lu, k=-1)
    print("Matriz: L = ", L)
    print("Comprobación: ||A-L@U||_2 = ", norm(A - L@U, 2)) 
else:
    print("Error ", lu)

Ejercicio 2-b.
Matriz: A =  [[  3  -2   6  -5]
 [ 18 -12  41 -39]
 [-27  18 -62  54]
 [  9  14  15 -47]]
Error  No existe la factorizacion LU


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3.</b></span> Escribir una función <span style="font-family: Courier">Python</span>, de nombre <span style="font-family: Courier">metodo_lu()</span>, que implemente el algoritmo del <b>método</b> $LU$ para resolver un sistema lineal $A\,X=B$.
    <br>
    Dicha función debe tener dos argumentos de entrada, que son la matriz $A$ y el(los) segundo(s) miembro(s) $X$, y dos argumentos de salida, siendo el primero de tipo boleano (para indicar si se ha resuelto o no el sistema) y el segundo la(s) solución(ones) del sistema en caso de éxito o un mensaje de error en caso contrario.
    </span></div>

In [9]:
def metodo_lu(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m!=n or n!=p or q < 1:
        return False, "Tamaños erróneos"
    exito, lu = facto_lu(A)
    if exito: 
        ex, Y = descenso1(lu,B)
        ex, X = remonte(lu, Y)
        return True, X
    else:
        return False, "Error metodo LU: error en la resolución"

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4.</b></span> Resolver mediante el método $LU$, si es posible, los siguientes sistemas lineales:
\[
\mbox{(a)} \quad \left(\begin{array}{rrrr} 2 & -1 & 4 & 0 \\ 4 & -1 & 5 & 1 \\ -2 & 2 & -2 & 3 \\ 0 & 3 & -9 & 4 \end{array} \right) \left( \begin{array}{c} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array} \right) =  \left( \begin{array}{r} 5 \\ 9 \\ 1 \\ -2 \end{array} \right)\,;
\qquad
\mbox{(b)} \quad \left(\begin{array}{rrrr} 3 & -2 & 6 & -5 \\ 24 & -12 & 41 & -39 \\ -27 & 18 & -62 & 54 \\ 9 & 14 & 15 & -47 \end{array} \right) \left( \begin{array}{c} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array} \right) =  \left( \begin{array}{r} 1 \\ 1 \\ 1 \\ 1 \end{array} \right)\,.
\]
    Comprobar la exactitud de los cálculos realizados, verificando que $B-A\,X=0$.
    <br>
    Calcular también,cuando sea posible, las inversas de las matrices dadas mediante el método $LU$.
    </span></div>

In [10]:
# Ejercicio 4-a.
print("Ejercicio 4-a.")
A = array([[2, -1, 4, 0], [4, -1, 5, 1], [-2, 2, -2, 3], [0, 3, -9, 4]])
print("Matriz: A = ", A)
B = array([[5], [9], [1], [-2]])
exito, X = metodo_lu(A,B)
if exito:
    print("Solución X = ", X)
    print("Comprobación: ||B-A@X||_2 = ", norma_vec(B-A@X,2))
else:
    print("Error: ", X)

Ejercicio 4-a.
Matriz: A =  [[ 2 -1  4  0]
 [ 4 -1  5  1]
 [-2  2 -2  3]
 [ 0  3 -9  4]]
Solución X =  [[1.]
 [1.]
 [1.]
 [1.]]
Comprobación: ||B-A@X||_2 =  0.0


In [11]:
# Ejercicio 4-b.
print("Ejercicio 4-b.")
A = array([[3, -2, 6, -5], [18, -12, 41, -39], [-27, 18, -62, 54], [9, 14, 15, -47]])
print("Matriz: A = ", A)
B = array([[1], [1], [1], [1]])
exito, X = metodo_lu(A,B)
if exito:
    print("Solución X = ", X)
    print("Comprobación: ||B-A@X||_2 = ", norma_vec(B-A@X,2))
else:
    print("Error: ", X)

Ejercicio 4-b.
Matriz: A =  [[  3  -2   6  -5]
 [ 18 -12  41 -39]
 [-27  18 -62  54]
 [  9  14  15 -47]]
Error:  Error metodo LU: error en la resolución


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Recordamos ahora que dada $A\in\mathcal{M}_n(\mathbb{R})$ simétrica e inversible, se llama <b>factorización de Cholesky</b> a la descomposición, si es posible, $A=C\,C^t$, siendo $C\in\mathcal{M}_n(\mathbb{R})$ triangular inferior e inversible. Esta factorización es posible si y solamente si la matriz $A$ es definida positiva, siendo además única si se impone que los elementos diagonales de $C$ sean positivos.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    La factorización de Cholesky de una matriz $A$, cuando es posible, está asociada de forma natural a un método directo de resolución del sistema $AX=B$, llamado <b>método de Cholesky</b>, en el que se pueden diferenciar dos etapas:<ul>
    <li>determinación de la factorización de Cholesky $A=C\,C^t$ de la matriz;</li>
    <li>resolución mediante un proceso de descenso seguido de uno de remonte del sistema lineal, ya que
\[
A\,X = B\quad \Longleftrightarrow\quad C\,Y = B \quad \mbox{y} \quad C^t\,X=Y\,.
\]</li></ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> Escribir una función <span style="font-family: Courier">Python</span>, de nombre <span style="font-family: Courier">facto_cholesky()</span>, que implemente el algoritmo de la <b>factorización de Cholesky</b> de una matriz $A$. Recordamos que para optimizar el número de operaciones que conducen a dicha factorización, utilizando el carácter simétrico de la matriz $A$, es importante hacer una impementación correcta de la relación
\[
a_{i,j} = \sum_{k=1}^i c_{i,k}\,c_{j,k}, \quad 1 \le i \le j \le n\,.
\]
    Haciendo $i=1,2,\ldots,n$ sucesivamente permite calcular las columnas de la matriz $C$.
    <br>
    La función creada debe tener un único argumento de entrada, que es la matriz $A$ y dos argumentos de salida, siendo el primero de tipo boleano (para indicar si se ha realizado o no dicha factorización) y el segundo una única matriz que debe contener en la parte triangular inferior la matriz $C$ y en la parte triangular superior la matrz $C^t$ (cuyos elementos diagonales son los mismos de los de la matriz $C$).
    </span></div>

In [19]:
def facto_cholesky(A):
    m, n = shape(A)
    if m != n:
        return False, "Error facto_cholesky: error en las dimensiones."
    if A.dtype == complex:
        return False, "Error facto_cholesky: matriz compleja."
    else:
        chol = array(A, dtype=float)
    for i in range(n):
        chol[i, i] -= sum(power(chol[i, :i], 2))
        if chol[i, i] >= 1e-100:
            chol[i, i] = sqrt(chol[i, i])
        else:
            return False, "Error facto_cholesky: no se factoriza la matriz"
        for j in range(i+1, n):
            chol[j, i] -= sum(chol[i, :i]*chol[j, :i])
            chol[j, i] = chol[j, i]/chol[i, i]
            chol[i, j] = chol[j, i]
    return True, chol

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 6.</b></span> Realizar, si es posible, la factorización de Cholesky de las siguientes matrices:
\[
\mbox{(a)} \quad A = \left(\begin{array}{rrrr} 1 & 2 & 3 & 4 \\ 2 & 5 & 1 & 10 \\ 3 & 1 & 35 & 5 \\ 4 & 10 & 5 & 45 \end{array} \right)\,;
\qquad
\mbox{(b)} \quad A = \left(\begin{array}{rrrr} 1 & 2 & 1 & 1 \\ 2 & 3 & 4 & 3 \\ 1 & 4 & -4 & 0 \\ 1 & 3 & 0 & 0 \end{array} \right)\,.
\]
    Comprobar la exactitud de los cálculos realizados, verificando que $A-C\,C^t=0$.
    </span></div>

In [21]:
# Ejercicio 6-a.
print("Ejercicio 6-a.")
A = array([[1, 2, 3, 4], [ 2, 5, 1, 10], [ 3, 1, 35, 5], [ 4, 10, 5, 45]])
print("Matriz: A = ", A)
exito, chol = facto_cholesky(A)
if exito:
    print("Factorización: chol = ", chol)
    C = tril(chol)
    print("Matriz: C = ", C)
    print("Comprobación: ||A-C@C^t||_2 = ", norm(A - C@transpose(C), 2)) #norma_mat
else:
    print("Error ", chol)

Ejercicio 6-a.
Matriz: A =  [[ 1  2  3  4]
 [ 2  5  1 10]
 [ 3  1 35  5]
 [ 4 10  5 45]]
Factorización: chol =  [[ 1.  2.  3.  4.]
 [ 2.  1. -5.  2.]
 [ 3. -5.  1.  3.]
 [ 4.  2.  3.  4.]]
Matriz: C =  [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3. -5.  1.  0.]
 [ 4.  2.  3.  4.]]
Comprobación: ||A-C@C^t||_2 =  0.0


In [22]:
# Ejercicio 6-b.
print("Ejercicio 6-a.")
A = array([[1, 2, 1, 1], [ 2, 3, 4, 3], [ 1, 4, -4, 0], [ 1, 3, 0, 0]])
print("Matriz: A = ", A)
exito, chol = facto_cholesky(A)
if exito:
    print("Factorización: chol = ", chol)
    C = tril(chol)
    print("Matriz: C = ", C)
    print("Comprobación: ||A-C@C^t||_2 = ", norm(A - C@transpose(C), 2)) #norma_mat
else:
    print("Error ", chol)

Ejercicio 6-a.
Matriz: A =  [[ 1  2  1  1]
 [ 2  3  4  3]
 [ 1  4 -4  0]
 [ 1  3  0  0]]
Error  Error facto_cholesky: no se factoriza la matriz


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 7.</b></span> Para las matrices del ejercicio anterior, coando sea posible, construir segundos miembros adecuados para que la solución del sistema resultante sea el vector de todas sus componentes iguales a 1 y resolver el sistema mediante el método de Cholesky.
    </span></div>

In [16]:
def metodo_cholesky(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m!=n or n!=p or q < 1:
        return False, "Tamaños erróneos"
    exito, chol = facto_cholesky(A)
    if exito: 
        ex, Y = descenso(chol,B)
        ex, X = remonte(chol, Y)
        return True, X
    else:
        return False, "Error metodo Cholesky: error en la resolución"

In [18]:
print("Ejercicio 7")
A = array([[1, 2, 3, 4], [ 2, 5, 1, 10], [ 3, 1, 35, 5], [ 4, 10, 5, 45]])
print("Matriz: A = ", A)
B=reshape(sum(A,axis=1),(4,1))
exito, X = metodo_cholesky(A,B)
if exito:
    print("Solución X = ", X)
    print("Comprobación: ||B-A@X||_2 = ", norma_vec(B-A@X,2))
else:
    print("Error: ", X)

Ejercicio 7
Matriz: A =  [[ 1  2  3  4]
 [ 2  5  1 10]
 [ 3  1 35  5]
 [ 4 10  5 45]]
Solución X =  [[1.]
 [1.]
 [1.]
 [1.]]
Comprobación: ||B-A@X||_2 =  0.0


**Ejercicio 8.** Considerar las matrices de Hilbert de orden $n=5,6,7,\ldots$, y tomar como segundo miembro la suma de las columnas de A. Evidentemente la solución del sistema resultante es el vector con todas las componentes igual a 1. Resolver los sistemas con el método de Cholesky y ver qué ocurre. (Observación: se puede demostrar que las matrices de Hilbert son simétricas y definidas positivas, por lo que admiten dicha factorización.)

Nota: Las matrices de Hilbert se caracterizan porque el patrón de generación de sus elementos responde a la siguiente estructura: 

$$H_{i,j}=\frac{1}{i+j-1}$$

$$
H_4=\begin{pmatrix} 1&\frac{1}{2}&\frac{1}{3}&\frac{1}{4}\\ 
\frac{1}{2}&\frac{1}{3}&\frac{1}{4}&\frac{1}{5}\\ 
\frac{1}{3}&\frac{1}{4}&\frac{1}{5}&\frac{1}{6}\\ 
\frac{1}{4}&\frac{1}{5}&\frac{1}{6}&\frac{1}{7}
\end{pmatrix}
$$

In [21]:
I=linspace(1,8,8)
J=reshape(I,(8,1))
A=1./(I+J-1)
print("Matriz: A = ", A)
B=reshape(sum(A,axis=1),(8,1))
exito, X = metodo_lu(A,B)
if exito:
    print("Solución X = ", X)
    print("Comprobación: ||B-A@X||_2 = ", norma_vec(B-A@X,2))
else:
    print("Error: ", X)

Matriz: A =  [[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125     ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1       ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333 0.07692308]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308 0.07142857]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  0.07142857 0.06666667]]
Solución X =  [[1.        ]
 [1.        ]
 [0.99999996]
 [1.00000019]
 [0.99999948]
 [1.00000073]
 [0.99999948]
 [1.00000015]]
Comprobación: ||B-A@X||_2 =  2.9373740229761033e-16
