<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En primer lugar cargamos los módulos necesarios.
    </span></div>

In [1]:
# -*- coding: utf-8 -*-
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El primer objetivo de esta práctica es ver la forma en la que podemos <b>definir nuestras propias funciones</b> que implementen un determinado algoritmo.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Por ejemplo, nos podemos plantear definir una función, a la que llamaremos <span style="font-family: Courier">conjugada()</span>, que calcule la <b>conjugada</b> de una matriz.
    <br>
    Esta función debe tener un único argumento de entrada, que es una matriz $A\in\mathcal{M}_{m\times n}(\mathbb{C})$, y debe devolver su matriz conjugada $A^*\in\mathcal{M}_{n\times m}(\mathbb{C})$. El código necesario para llevar a cabo esta tarea puede ser tan simple como este que sigue.
    </span></div>

In [2]:
def conjugada(A):
    return conjugate(transpose(A))

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Calcular las conjugadas de las matrices: (a) $A = \left( \begin{array}{cc} 1 & 4\,i \\ 2 & -5\,i \\ 3 & 6+6\,i \end{array} \right)$; (b) $B = \left( \begin{array}{cc} 1 & 4\,i \end{array} \right)$; (c) $C = \left( \begin{array}{c} 1 \\ 2 \\ 3 \end{array} \right)$.
    </span></div>

In [3]:
# Ejercicio 1-a.
print("Ejercicio 1-a.")
A = array([[1, 4j], [2, -5j], [3, 6+6j]])
print("Matriz: A = ", A)
print("Conjugada: A^* = ", conjugada(A))

Ejercicio 1-a.
Matriz: A =  [[ 1.+0.j  0.+4.j]
 [ 2.+0.j -0.-5.j]
 [ 3.+0.j  6.+6.j]]
Conjugada: A^* =  [[ 1.-0.j  2.-0.j  3.-0.j]
 [ 0.-4.j -0.+5.j  6.-6.j]]


In [4]:
# Ejercicio 1-b.
print("Ejercicio 1-b.")
B = array([[1, 4j]])
print("Conjugada: B^* = ", conjugada(B))

Ejercicio 1-b.
Conjugada: B^* =  [[1.-0.j]
 [0.-4.j]]


In [5]:
# Ejercicio 1-c.
print("Ejercicio 1-c.")
C = array([[1], [2], [3]])
print("Conjugada: C^* = ", conjugada(C))

Ejercicio 1-c.
Conjugada: C^* =  [[1 2 3]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Mejorar la función anterior en el siguiente sentido: como se puede comprobar, si el argumento de entrada es un vector (array de una dimensión), la función devuelve también un vector con los elementos conjugados; modificar la función creada para que en este caso considere el vector como una matriz fila y devuelva, por tanto, una matriz columna (evidentemente con los elementos conjugados).
    <br>
    Comprobar la validez de la mejora realizada utilizando el vector $x=(1+i\,,\,2-2\,i\,,\,-3+3\,i)$.
    </span></div>

In [4]:
# Ejercicio 2.
print("Ejercicio 2.")
x = array([1+1j, 2-2j, -3+3j])

def conjugada(A):
    if ndim(A)==1:
        A = array([A])
    return conjugate(transpose(A))


print("Conjugada: x^* = ", conjugada(x))


Ejercicio 2.
Conjugada: x^* =  [[ 1.-1.j]
 [ 2.+2.j]
 [-3.-3.j]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El siguiente objetivo de esta práctica es calcular los <b>autovalores</b> y <b>autovectores</b> de una matriz, <b>diagonalizarla</b> (si es posible) y calcular sus <b>valores singulares</b>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
   Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>autovalores</b> y <b>autovectores</b> pueden calcularse con la ayuda de la función <span style="font-family: Courier">eig()</span>; esta función tiene un único argumento de entrada que es la matriz cuadrada $A$ y tiene dos argumentos de salida, siendo el primero un vector de $n$ componentes conteniendo a los autovalores (en un orden arbitrario, quizás números complejos aunque la matriz sea de coeficientes reales y repetidos en caso de multiplicidad mayor que uno) y el segundo una matriz cuadrada de orden $n$ cuyas columnas son autovectores (asociados a los autovalores calculados, en el mismo orden y unitarios respecto del producto escalar ordinario).
    <br>
    No obstante la matriz de autovectores puede no ser regular en el caso de que la matriz dada no sea diagonalizable (los autovectores asociados a autovalores con multiplicidad mayor que 1 no son linealmente independientes).
    <br>
    En el caso de que la matriz dada sí sea diagonalizable, la matriz de autovectores que obtenemos es regular, pero aunque tengamos asegurado que existe una matriz de paso ortogonal-unitaria (al ser la matriz dada normal), la que obtenemos no lo es necesariamente.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (a).</b></span> Calcular los autovalores y autovectores, y ver si es diagonalizable la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    <br>
    Imprimir el vector de autovalores y la matriz de autovectores (ortogonal-unitaria si es posible) y comprobar si la matriz dada es diagonalizable (comprobar que $P^{-1}\,A\,P=D$ para lo cual se puede utilizar la función <span style="font-family: Courier">inv()</span> que calcula la inversa de la función dada como argumento). 
    </span></div>

In [10]:
# Ejercicio 3-a.
print("Ejercicio 3-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-a.
Matriz: A =  [[3 1]
 [0 1]]
Vector de autovalores: d =  [3. 1.]
Matriz de autovectores: P =  [[ 1.         -0.4472136 ]
 [ 0.          0.89442719]]
det(P) =  0.8944271909999159
La matriz es diagonalizable.
inv(P)@A@P =  [[3. 0.]
 [0. 1.]]
Comprobación:  0.0


In [11]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = ", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A =  [[ 1 -2]
 [-2 -1]]
La matriz no es normal.


In [12]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = ", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P =  [[ 1.        -0.4472136]
 [-0.4472136  1.       ]]
La matriz de paso no es ortogonal-unitaria.


In [13]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i])

Autovalor: lambda =  3.0  Autovector: x =  [1. 0.]
Autovalor: lambda =  1.0  Autovector: x =  [-0.4472136   0.89442719]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (b).</b></span> Ídem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [14]:
# Ejercicio 3-b.
print("Ejercicio 3-b.")
A = array([[0, -2], [2, 0]])
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-b.
Matriz: A =  [[ 0 -2]
 [ 2  0]]
Vector de autovalores: d =  [0.+2.j 0.-2.j]
Matriz de autovectores: P =  [[ 0.        -0.70710678j  0.        +0.70710678j]
 [-0.70710678+0.j         -0.70710678-0.j        ]]
det(P) =  1j
La matriz es diagonalizable.
inv(P)@A@P =  [[0.+2.0000000e+00j 0.+4.4408921e-16j]
 [0.-4.4408921e-16j 0.-2.0000000e+00j]]
Comprobación:  4.440892098500626e-16


In [15]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = ", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A =  [[0 0]
 [0 0]]
La matriz es normal.


In [16]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = ", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P =  [[1.00000000e+00+0.j 2.22044605e-16+0.j]
 [2.22044605e-16+0.j 1.00000000e+00+0.j]]
La matriz de paso es ortogonal-unitaria.


In [17]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i])

Autovalor: lambda =  2.0000000000000004j  Autovector: x =  [ 0.        -0.70710678j -0.70710678+0.j        ]
Autovalor: lambda =  -2.0000000000000004j  Autovector: x =  [ 0.        +0.70710678j -0.70710678-0.j        ]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (c).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [18]:
# Ejercicio 3-c.
print("Ejercicio 3-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-c.
Matriz: A =  [[ 2  0  2]
 [ 0  1  0]
 [ 2  0 -1]]
Vector de autovalores: d =  [ 3. -2.  1.]
Matriz de autovectores: P =  [[ 0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [ 0.4472136   0.89442719  0.        ]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P =  [[ 3.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobación:  2.220446049250313e-16


In [20]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = ", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A =  [[0 0 0]
 [0 0 0]
 [0 0 0]]
La matriz es normal.


In [21]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = ", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
La matriz de paso es ortogonal-unitaria.


In [19]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i])

Autovalor: lambda =  3.0  Autovector: x =  [0.89442719 0.         0.4472136 ]
Autovalor: lambda =  -2.0  Autovector: x =  [-0.4472136   0.          0.89442719]
Autovalor: lambda =  1.0  Autovector: x =  [0. 1. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (d).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [22]:
# Ejercicio 3-d.
print("Ejercicio 3-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-d.
Matriz: A =  [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P =  [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]
det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.


In [23]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = ", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A =  [[-25  28   0]
 [ 28 -40 -12]
 [  0 -12  65]]
La matriz no es normal.


In [24]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = ", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P =  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
La matriz de paso no es ortogonal-unitaria.


In [25]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i])

Autovalor: lambda =  1.0  Autovector: x =  [0. 0. 1.]
Autovalor: lambda =  1.0  Autovector: x =  [0.00000000e+00 3.17206578e-17 1.00000000e+00]
Autovalor: lambda =  1.0  Autovector: x =  [2.34780031e-33 3.17206578e-17 1.00000000e+00]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (e).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [26]:
# Ejercicio 3-e.
print("Ejercicio 3-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-e.
Matriz: A =  [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de autovalores: d =  [6.00000000e+00 1.00000000e+00 4.59534891e-17 1.00000000e+00]
Matriz de autovectores: P =  [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 3.65148372e-01  4.47213595e-01  8.16496581e-01  0.00000000e+00]
 [-9.12870929e-01  6.94835567e-17  4.08248290e-01  0.00000000e+00]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P =  [[ 6.00000000e+00 -6.02621719e-16  4.44089210e-16  0.00000000e+00]
 [-3.90242926e-16  1.00000000e+00  1.19010791e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobación:  6.026217186954206e-16


In [27]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = ", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A =  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
La matriz es normal.


In [28]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = ", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P =  [[ 1.00000000e+00 -7.91836773e-18  1.66533454e-16  0.00000000e+00]
 [-7.91836773e-18  1.00000000e+00  2.83665432e-17  0.00000000e+00]
 [ 1.66533454e-16  2.83665432e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
La matriz de paso es ortogonal-unitaria.


In [29]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i])

Autovalor: lambda =  6.0  Autovector: x =  [-0.18257419  0.          0.36514837 -0.91287093]
Autovalor: lambda =  1.0000000000000002  Autovector: x =  [8.94427191e-01 0.00000000e+00 4.47213595e-01 6.94835567e-17]
Autovalor: lambda =  4.595348908876999e-17  Autovector: x =  [-0.40824829  0.          0.81649658  0.40824829]
Autovalor: lambda =  1.0  Autovector: x =  [0. 1. 0. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (f).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [30]:
# Ejercicio 3-f.
print("Ejercicio 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-f.
Matriz: A =  [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P =  [[-0.8660254   0.5        -0.11095038 -0.06189687]
 [ 0.28867513  0.5         0.84675161  0.47238482]
 [ 0.28867513  0.5        -0.36790061 -0.79208773]
 [ 0.28867513  0.5        -0.36790061  0.38159978]]
det(P) =  0.8230833252150771
La matriz es diagonalizable.
inv(P)@A@P =  [[ 6.00000000e+00  0.00000000e+00  2.22044605e-16 -2.22044605e-16]
 [-6.66133815e-16  1.00000000e+01 -2.22044605e-16 -6.66133815e-16]
 [ 4.44089210e-16  8.88178420e-16  6.00000000e+00  1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  6.00000000e+00]]
Comprobación:  1.3322676295501878e-15


In [31]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = ", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La matriz es normal.


In [32]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = ", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P =  [[1.00000000e+00 0.00000000e+00 1.28114463e-01 7.14723506e-02]
 [0.00000000e+00 1.00000000e+00 1.11022302e-16 2.77555756e-17]
 [1.28114463e-01 1.11022302e-16 1.00000000e+00 5.57878859e-01]
 [7.14723506e-02 2.77555756e-17 5.57878859e-01 1.00000000e+00]]
La matriz de paso no es ortogonal-unitaria.


In [33]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i])

Autovalor: lambda =  6.0  Autovector: x =  [-0.8660254   0.28867513  0.28867513  0.28867513]
Autovalor: lambda =  10.0  Autovector: x =  [0.5 0.5 0.5 0.5]
Autovalor: lambda =  5.999999999999999  Autovector: x =  [-0.11095038  0.84675161 -0.36790061 -0.36790061]
Autovalor: lambda =  6.0  Autovector: x =  [-0.06189687  0.47238482 -0.79208773  0.38159978]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>valores singulares</b> pueden calcularse con la ayuda de la función <span style="font-family: Courier">svd()</span>; esta función tiene un único argumento de entrada que es la matriz cuadrada $A$ y tiene tres argumentos de salida, siendo el segundo un vector de $n$ componentes (reales y mayores o iguales que 0) conteniendo a los valores singulares (en un orden arbitrario y repetidos en caso de multiplicidad mayor que uno) y el primero y tercero las  dos matrices de orden $n$ ortogonales-unitarias de su descomposición en valores singulares.
    <br>
    Si llamamos $S$ a la matriz diagonal cuyos elementos diagonales son los valores singulares de $A$ (en el orden que proporciona la función <span style="font-family: Courier">svd()</span>) y $U$ y $V$ las matrices ortogonales-unitarias que se obtienen como primera y tercera salida de dicha función, se verifica que $U\,S\,V=A$.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (a).</b></span> Realizar la descomposición en valores singulares de la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    </span></div>

In [34]:
# Ejercicio 4-a.
print("Ejercicio 4-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = ", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = ", U)
print("V = ", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = ", DVS)
print("Comprobación: ", max(abs(DVS - A)))

Ejercicio 4-a.
Matriz: A =  [[3 1]
 [0 1]]
Vector de valores singulares: s =  [3.1795868  0.94351882]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U =  [[ 0.99402894 -0.10911677]
 [ 0.10911677  0.99402894]]
V =  [[ 0.93788501  0.34694625]
 [-0.34694625  0.93788501]]
U@diag(s)@V =  [[3. 1.]
 [0. 1.]]
Comprobación:  8.881784197001252e-16


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (b).</b></span> Ídem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [35]:
# Ejercicio 4-b.
print("Ejercicio 4-b.")
A = array([[0, -2], [2, 0]])
print("Matriz: A = ", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = ", U)
print("V = ", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = ", DVS)
print("Comprobación: ", max(abs(DVS - A)))

Ejercicio 4-b.
Matriz: A =  [[ 0 -2]
 [ 2  0]]
Vector de valores singulares: s =  [2. 2.]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U =  [[ 0. -1.]
 [-1.  0.]]
V =  [[-1. -0.]
 [ 0.  1.]]
U@diag(s)@V =  [[ 0. -2.]
 [ 2.  0.]]
Comprobación:  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (c).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [36]:
# Ejercicio 4-c.
print("Ejercicio 4-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = ", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = ", U)
print("V = ", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = ", DVS)
print("Comprobación: ", max(abs(DVS - A)))

Ejercicio 4-c.
Matriz: A =  [[ 2  0  2]
 [ 0  1  0]
 [ 2  0 -1]]
Vector de valores singulares: s =  [3. 2. 1.]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U =  [[-0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [-0.4472136   0.89442719  0.        ]]
V =  [[-0.89442719  0.         -0.4472136 ]
 [ 0.4472136   0.         -0.89442719]
 [ 0.          1.          0.        ]]
U@diag(s)@V =  [[ 2.  0.  2.]
 [ 0.  1.  0.]
 [ 2.  0. -1.]]
Comprobación:  1.7763568394002505e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (d).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [37]:
# Ejercicio 4-d.
print("Ejercicio 4-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = ", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = ", U)
print("V = ", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = ", DVS)
print("Comprobación: ", max(abs(DVS - A)))

Ejercicio 4-d.
Matriz: A =  [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de valores singulares: s =  [8.49406432 2.20182024 0.05346907]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U =  [[-0.06601923  0.37536832 -0.92452154]
 [ 0.29463434 -0.87789606 -0.3774773 ]
 [-0.95332684 -0.29731656 -0.05263838]]
V =  [[-0.56077155  0.8203284  -0.11223447]
 [ 0.82649357  0.54651139 -0.13503217]
 [-0.0494333  -0.16848327 -0.98446419]]
U@diag(s)@V =  [[ 1.00000000e+00  1.58143382e-15 -2.78226301e-16]
 [-3.00000000e+00  1.00000000e+00  2.65531314e-16]
 [ 4.00000000e+00 -7.00000000e+00  1.00000000e+00]]
Comprobación:  1.7763568394002505e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (e).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [38]:
# Ejercicio 4-e.
print("Ejercicio 4-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = ", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = ", U)
print("V = ", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = ", DVS)
print("Comprobación: ", max(abs(DVS - A)))

Ejercicio 4-e.
Matriz: A =  [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de valores singulares: s =  [6.000000e+00 1.000000e+00 1.000000e+00 1.128133e-16]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U =  [[-1.82574186e-01  8.94427191e-01 -7.25938612e-17 -4.08248290e-01]
 [ 0.00000000e+00 -2.22044605e-16 -1.00000000e+00 -2.22044605e-16]
 [ 3.65148372e-01  4.47213595e-01 -6.40987562e-17  8.16496581e-01]
 [-9.12870929e-01 -2.90131299e-17 -1.01405595e-16  4.08248290e-01]]
V =  [[-1.82574186e-01  0.00000000e+00  3.65148372e-01 -9.12870929e-01]
 [ 8.94427191e-01 -2.22044605e-16  4.47213595e-01 -5.06007537e-17]
 [-1.73999456e-16 -1.00000000e+00 -1.11022302e-16 -1.11022302e-16]
 [ 4.08248290e-01 -2.77555756e-17 -8.16496581e-01 -4.08248290e-01]]
U@diag(s)@V =  [[ 1.00000000e+00 -1.26008871e-16  5.55111512e-16  1.00000000e+00]
 [-2.46032764e-17  1.00000000e+00  1.17209363e-17  1.11022302e-16]
 [ 0.00000000e+00 -3.52026099e-17  1.00000000e+00 

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (f).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [39]:
# Ejercicio 4-f.
print("Ejercicio 4-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = ", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = ", U)
print("V = ", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = ", DVS)
print("Comprobación: ", max(abs(DVS - A)))

Ejercicio 4-f.
Matriz: A =  [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de valores singulares: s =  [10.  6.  6.  6.]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U =  [[-5.00000000e-01  8.66025404e-01  0.00000000e+00 -5.46986163e-17]
 [-5.00000000e-01 -2.88675135e-01 -8.75605293e-17  8.16496581e-01]
 [-5.00000000e-01 -2.88675135e-01 -7.07106781e-01 -4.08248290e-01]
 [-5.00000000e-01 -2.88675135e-01  7.07106781e-01 -4.08248290e-01]]
V =  [[-5.00000000e-01 -5.00000000e-01 -5.00000000e-01 -5.00000000e-01]
 [ 8.66025404e-01 -2.88675135e-01 -2.88675135e-01 -2.88675135e-01]
 [ 0.00000000e+00 -6.99362418e-17 -7.07106781e-01  7.07106781e-01]
 [ 0.00000000e+00  8.16496581e-01 -4.08248290e-01 -4.08248290e-01]]
U@diag(s)@V =  [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Comprobación:  3.1086244689504383e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> En aquellos casos del Ejercicio 3 en los que hay autovalores con multiplicidad (dimensión algebraica) mayor que 1, comprobar cuando la dimensión geométrica de los mismos es igual o no (y por tanto la matriz es o no diagonalizable).
    <br>
    <i>Indicación:</i> la función <span style="font-family: Courier">matrix_rank()</span>, cuyo parámetro de entrada es una matriz (no necesariamente cuadrada), devuelve el rango de la misma.
    </span></div>

In [40]:
# Ejercicio 3-d.
print("Ejercicio 3-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-d.
Matriz: A =  [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P =  [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]
det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.


In [41]:
# Ejercicio 5.
print("El autovalor 1 tiene multiplicidad (dimensión algebraica) 3.")
dg = matrix_rank(P)
print("Su dimensión geométrica es ", dg)
print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimensión algebraica) 3.
Su dimensión geométrica es  1
Por tanto la matriz no es diagonalizable.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 6.</b></span> En aquellos casos del Ejercicio 3 en los que la matriz es normal y por tanto diagonalizable con matriz de paso unitaria, pero la matriz de paso obtenida no lo es, obtener una nueva matriz de paso que sí lo sea.
    <br>
    <i>Indicación:</i> la función <span style="font-family: Courier">qr()</span>, cuyo parámetro de entrada es una matriz (no necesariamente cuadrada), devuelve dos matrices, siendo la primera de ellas la ortonormalización de Gram-Schmidt de los vectores columnas de la matriz dada.
    </span></div>

In [2]:
# Ejercicio 3-f.
print("Ejercicio 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = ", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = ", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-f.
Matriz: A =  [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P =  [[-0.8660254   0.5        -0.11095038 -0.06189687]
 [ 0.28867513  0.5         0.84675161  0.47238482]
 [ 0.28867513  0.5        -0.36790061 -0.79208773]
 [ 0.28867513  0.5        -0.36790061  0.38159978]]
det(P) =  0.8230833252150771
La matriz es diagonalizable.
inv(P)@A@P =  [[ 6.00000000e+00  0.00000000e+00  2.22044605e-16 -2.22044605e-16]
 [-6.66133815e-16  1.00000000e+01 -2.22044605e-16 -6.66133815e-16]
 [ 4.44089210e-16  8.88178420e-16  6.00000000e+00  1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  6.00000000e+00]]
Comprobación:  1.3322676295501878e-15


In [6]:
#Ejercicio 6
P, a = qr(P)
print(P)
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = ", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1.e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = ", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

[[-8.66025404e-01 -5.00000000e-01 -5.17926092e-17  6.19757006e-19]
 [ 2.88675135e-01 -5.00000000e-01  8.16496581e-01 -8.76564061e-17]
 [ 2.88675135e-01 -5.00000000e-01 -4.08248290e-01 -7.07106781e-01]
 [ 2.88675135e-01 -5.00000000e-01 -4.08248290e-01  7.07106781e-01]]
P^*@P =  [[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00 -8.32667268e-17  0.00000000e+00]
 [ 0.00000000e+00 -8.32667268e-17  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16  1.00000000e+00]]
La matriz de paso es ortogonal-unitaria.
det(P) =  -0.9999999999999998
La matriz es diagonalizable.
inv(P)@A@P =  [[ 6.00000000e+00 -8.88178420e-16 -1.11022302e-16  0.00000000e+00]
 [-4.44089210e-16  1.00000000e+01  8.88178420e-16  0.00000000e+00]
 [ 0.00000000e+00  8.88178420e-16  6.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  6.00000000e+00]]
Comprobación:  8.881784197001252e-16


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 7.</b></span> Para la matriz $A = \left( \begin{array}{rrr} 1 & 2 & 3 \\ 4 & 5 & 6\\ 7 & 8 & 9 \end{array} \right)$, comprobar que los valores singulares de $A$ son efectivamente las raíces cuadradas positivas de los autovalores de $A^*\,A$.
    </span></div>

In [15]:
A=array([[1,2,3],[4,5,6],[7,8,9]])
d, P = eig(conjugada(A)@A)
U, s, V = svd(A)
print("autovalores de A*A:", d)
print("valores singulares de A: ", s)
print("Comprobación: ", max(abs(d - s*s)))


autovalores de A*A: [2.83858587e+02 1.14141342e+00 1.03583089e-15]
valores singulares de A:  [1.68481034e+01 1.06836951e+00 3.33475287e-16]
Comprobación:  1.7053025658242404e-13


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Importante.</b></span> Durante el desarrollo de las clases prácticas vamos a crear un fichero <span style="font-family: Courier">Python</span>, al que daremos el nombre de <span style="font-family: Courier">algoritmos.py</span>, donde almacenaremos todas aquellas funciones propias que definamos durante el curso; esta será la <b>biblioteca</b> de nuestras funciones. A partir de ese momento, podremos utilizar dichas funciones en cualquier hoja de trabajo que estemos utilizando, sin más que importar dicho fichero al principio de la hoja de trabajo con una instrucción del tipo <span style="font-family: Courier">from algoritmos import *</span>.
    <br>
    Cada vez que se modifique dicho fichero, no debemos olvidar guardar su contenido y reinicializar el núcleo de la hoja de trabajo para tener en cuenta dichas modificaciones.
    </span></div>